name: open_meteo_dart
description: A client for [open-meteo](https://open-meteo.com/) API written in dart.
version: 0.0.1
repository: https://github.com/timosturm/open-meteo-dart
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  dio: ^5.1.2
  json_annotation: ^4.8.1
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.4  # `dart run build_runner build`
  json_serializable: ^6.7.0